kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-aspcoreweb-svc
spec:
  selector:
    app: aspcoreweb
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer