kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nodeapi-svc
spec:
  selector:
    app: nodeapi
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080